### PR TITLE
Added AbstractCalculator abstract type.

### PR DESCRIPTION
**Pull request by CedricTravelletti**
This PR adds an AbstractCalculator abstract type to the AtomsCalculators interface. 

(this is part of the effort to develop a geometry optimization package for the JuliaMolSim ecosystem [https://github.com/CedricTravelletti/GeomOpt.jl](https://github.com/CedricTravelletti/GeomOpt.jl)).

### CODE REVIEW

**Comment by cortner** [comment]
Why is this needed? Are you planning to dispatch on it in geometry optimisation? That should not be required.

**Comment by mfherbst** [comment]
I agree with Christoph. Should be no need for this @CedricTravelletti .

**Comment by cortner** [comment]
@CedricTravelletti  -- Maybe the confusion is that you think you need to have `AbstractCalculator` in the type signature. That's a common misconception even among experienced Julia programmers. In fact you only need that the "calculators" implement the methods you will call. 

A type hierarchy is usually only imposed when different concrete types share functionality, and even then it isn't always the best solution. Type hierarchies restrict what you can do and we try to avoid them until needed.

**Comment by cortner** [comment]
I think I first learned this from David Sanders in my earlier Julia days. We filled a matrix with some weird custom and just called matrix-vector multiplication. It then said you need to implement `zero` for this object, or maybe it was `one`, and then `*` and so forth. Once we had all the methods overloaded, the mat-vec just worked. No subtyping required. It was a good learning experience.

**Pull request closed without merging**
